config_json: |
    {
        "192.168.1.11": {
            "pose_ids": [1, 2, 3],
            "adapter": "reolink-823S2",
            "id": "1",
            "name": "example-station-01",
            "bbox_mask_url": "",
            "poses": [
                0,
                1,
                2
            ],
            "token": "",
            "type": "ptz"
        },
        "192.168.1.12": {
            "pose_ids": [4, 5, 6, 7],
            "adapter": "reolink-823S2",
            "id": "2",
            "name": "example-station-02",
            "bbox_mask_url": "",
            "poses": [
                0,
                1,
                2,
                3
            ],
            "token": "",
            "type": "ptz"
        }
    }

static_ip_interface: eth0
static_ip_address: 192.168.1.99
static_ip_gateway: 192.168.1.1
